In [2]:
pip install preamble

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement preamble (from versions: none)
ERROR: No matching distribution found for preamble


In [1]:
from preamble import *
%matplotlib inline

ModuleNotFoundError: No module named 'preamble'

# Numpy

In [3]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
print("x:\n{}".format(x))

x:
[[1 2 3]
 [4 5 6]]


# SciPy


In [4]:
from scipy import sparse

# Create a 2D NumPy array with a diagonal of ones, and zeros everywhere else
eye = np.eye(4)
print("NumPy array:\n", eye)

NumPy array:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
sparse_matrix = sparse.csr_matrix(eye)
print("\nScipPy sparse CSR matrix:\n",sparse_matrix)


ScipPy sparse CSR matrix:
   (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
